project:
  type: website
  render:
    - index.qmd 
    - about.qmd
  output-dir: docs

website:
  title: "ETC5543-VNPA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



