project:
  type: website
  render:
    - index.qmd 
    - about.qmd
    - report/proposal.qmd
    - analysis/eda_LAF_speciesgroup.qmd
  output-dir: docs

website:
  title: "ETC5543-VNPA"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: About
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Project proposal"
        contents:
          - report/proposal.qmd
          - analysis/eda_LAF_speciesgroup.qmd
          
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



