---
title: "`EDA on Southern Brown Bandicoot sightings in Victoria`"
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 2
editor: source
execute:
  echo: false
  message: false
  warning: false
---

```{r library}
# Library
lib <- c("targets","tidyverse","sf","galah","tmap","leaflet","plotly")
invisible(lapply(lib, library, character.only = TRUE))
rm(lib)
```

# Get data

```{r get-data}
# 1. Wildlife sightings --------------------------------------------------------
# 1.1 ALA
tar_load(ala_sbb_raw)

# 1.2 VBA
tar_load(vba_fauna_sbb)

# Parks boundary ---------------------------------------------------------------
tar_load(parkres)
bbox_bunyip <- st_bbox(parkres |> filter(NAME == "Bunyip State Park")) 

# Victoria map SA2
tar_load(vic_map)
```

# Process Data 

```{r}
# VBA_SBB sighting within parkres areas 
vba_sbb_parkres <- st_join(vba_fauna_sbb, parkres[,"NAME"], 
                           join = st_within, left = FALSE) |> # inner join 
  dplyr::filter(START_YEAR > 1999) |> 
  dplyr::rename(PARKRES_NAME = NAME)

# Select fire POLYONS contains sighting POINTS
# tar_load(fire_history)
fire_history_subset <- tar_read(fire_history)[vba_sbb_parkres,] # fire_history[vba_sbb_parkres,]

# Select evc POLYONS contains sighting POINTS
evc_subset <- tar_read(evc)[vba_sbb_parkres,] # evc[vba_sbb_parkres,]

vba_sbb_full <-
  vba_sbb_parkres |> 
 # Join sightings (within parkres) with fire history 
  st_join(fire_history_subset[, c("FIRETYPE", "FIRE_SEASON", "FIRE_NO", "FIRE_SVRTY")],
          join = st_within, left = TRUE) |> 
 # Join with EVC 
  st_join(evc_subset[, c("EVC", "XGROUPNAME")],
          join = st_within, left = TRUE) |> 
  rename(FIRE_TYPE = FIRETYPE,
         FIRE_SEVERITY = FIRE_SVRTY,
         EVC_GROUPNAME = XGROUPNAME) |> 
 # Get the latest fire of each sighting
  arrange(RECORD_ID, desc(FIRE_SEASON), desc(FIRE_NO)) |> 
  group_by(RECORD_ID) |>
  dplyr::slice_head(n=1) |>
 # Add and mutate columns
  dplyr::mutate(
    FIRE_AGE = 
      dplyr::if_else(START_YEAR - FIRE_SEASON < 0, NA, START_YEAR - FIRE_SEASON),
    FIRE_TYPE = dplyr::if_else(is.na(FIRE_AGE), NA, FIRE_TYPE),
    FIRE_SEASON = dplyr::if_else(is.na(FIRE_AGE), NA, FIRE_SEASON),
    FIRE_NO = dplyr::if_else(is.na(FIRE_AGE), NA, FIRE_NO),
    FIRE_AGE_CATE = case_when(
      is.na(FIRE_AGE) ~ "5. Unburnt",
      FIRE_AGE < 4 ~ "1. Recent",
      FIRE_AGE < 10 ~ "2. Early",
      FIRE_AGE < 34 ~ "3. Medium",
      TRUE ~ "4. Long"
    )
  )

```

# Data sources: ALA v. VBA

```{r}
#| eval: false 

# Plot: sightings all time
ggplot() + 
  geom_sf(data = vic_map) +
  geom_sf(data = ala_sbb_raw,
          color = "limegreen") +
  # facet_wrap(~vba_fauna1_agile$START_YEAR) + 
  labs(title = "Southern Brown Bandicoot sightings, all time",
       subtitle = "ALA")

ggplot() + 
  geom_sf(data = vic_map) +
  geom_sf(data = vba_fauna_sbb,
          color = "limegreen") +
  # coord_sf(xlim = bbox[c("xmin", "xmax")], ylim = bbox[c("ymin", "ymax")]) + # Zoom
  # facet_wrap(~vba_fauna1_agile$START_YEAR) + 
  labs(title = "Southern Brown Bandicoot sightings, all time",
       subtitle = "VBA")

# Plot: since 2019
ggplot() + 
  geom_sf(data = vic_map) +
  geom_sf(data = ala_sbb_raw |> filter(Year > 2008),
          color = "limegreen") +
  coord_sf(xlim = bbox_bunyip[c("xmin", "xmax")], ylim = bbox_bunyip[c("ymin", "ymax")]) + # Zoom Bunyip
  # coord_sf(xlim = c(145, 146), ylim = c(-38.4,-38.0)) + # Zoom
  facet_wrap(~Year) +
  labs(title = "Southern Brown Bandicoot sightings, since 2019",
       subtitle = "ALA")

ggplot() + 
  geom_sf(data = vic_map) +
  geom_sf(data = vba_fauna_sbb |> filter(START_YEAR > 2007),
          color = "limegreen") +
  # coord_sf(xlim = bbox_bunyip[c("xmin", "xmax")], ylim = bbox_bunyip[c("ymin", "ymax")]) + # Zoom Bunyip
  # coord_sf(xlim = c(145, 146), ylim = c(-38.4,-38.0)) + # Zoom
  facet_wrap(~START_YEAR) +
  labs(title = "Southern Brown Bandicoot sightings, since 2019",
       subtitle = "VBA")
```

```{r try-leaflet}
# # try leaftlet -> too slow
# # Reproject GSA2020 to EPSG:4326
# vic_map_4326 <- st_transform(vic_map, 4326)
# ala_sbb_raw_4326 <- st_transform(ala_sbb_raw, 4326)
# # st_crs(vic_map_4326)
# 
# leaflet() |>
#   addPolygons(data = vic_map_4326) |> 
#   addCircleMarkers(data = ala_sbb_raw_4326, popup = ~Year)
```

# Parks 

```{r}
# ALA_SBB sighting within parkres areas 
st_crs(ala_sbb_raw) <- st_crs(parkres)
ala_sbb_parkres <- 
  st_join(ala_sbb_raw, parkres[,"NAME"], 
          join = st_within, left = FALSE) |> # inner join
  rename(PARKRES_NAME = NAME)

# Spatial distribution 
ggplot() +
  geom_sf(data = vic_map) + 
  geom_sf(data = parkres, fill=alpha("limegreen",0.5)) +
  geom_sf(data = ala_sbb_parkres |> filter(Year > 1999), 
          color = "maroon", size = 1)

# Count 
ala_sbb_parkres |> st_drop_geometry() |> 
  group_by(Year) |> summarise(count_obs = n()) |> 
  filter(Year > 1999) |> 
  ggplot(aes(x=Year, y =count_obs)) +
  geom_col(fill = "maroon") + 
  geom_text(aes(label = count_obs), vjust = -0.5) +
  labs(title = "Southern Brown Bandicoot sightings within parks",
       subtitle = "ALA")
```


```{r}
# Spatial distribution 
ggplot() +
  geom_sf(data = vic_map) + 
  geom_sf(data = parkres, fill=alpha("limegreen",0.5)) +
  geom_sf(data = vba_sbb_parkres, 
          color = "tan1", size = 1)

# Count 
vba_sbb_parkres |> st_drop_geometry() |> 
  group_by(START_YEAR) |> summarise(count_obs = n()) |> 
  ggplot(aes(x=START_YEAR, y =count_obs)) +
  geom_col(fill = "tan1") + 
  geom_text(aes(label = count_obs), vjust = -0.5) +
  labs(title = "Southern Brown Bandicoot sightings within parks",
       subtitle = "VBA")
```
 
# Interactive map

```{r plotly}
#| eval: false 
map <- ggplot() + 
  geom_sf(data = vic_map, fill = "grey95", color = "grey70") +
  geom_sf(data = ala_sbb_raw |> filter(Year > 2018),
          aes(color = as.factor(Year)))

ggplotly(map) |> 
  layout(title = "ALA: Southern Brown Bandicoot sightings, since 2019")
```

```{r}
#| eval: false 
# Create bounding box (bbox) 
# bbox <- st_bbox(vic_map)
bbox <- st_bbox( c(xmin = 145.540805, ymin = -38.026482, xmax = 145.846244, ymax = -37.882282), 
                 crs = st_crs(vic_map) )

# tmap_mode("view") # Turn on interactive map
# tmap_mode("plot") # Turn off interactive map
ala_sbb_2018 <- ala_sbb_raw |> filter(Year >= 2018)

tm_shape(vic_map, bbox = bbox_bunyip) + # Zoom in with bbox
  tm_fill(col = "grey90") + 
  tm_borders(col = "white") + 
  tm_shape(vba_fauna_sbb |> filter(START_YEAR > 2018)) +
  tm_symbols(size = 1, col = "limegreen") +
  tm_facets(by = "START_YEAR")
```


# Fire history 

```{r}
vba_sbb_full |> 
  st_drop_geometry() |>
  group_by(FIRE_AGE_CATE,START_YEAR) |> 
  summarise(COUNT_SIGHTING = n()) |> 
  ggplot(aes(x = FIRE_AGE_CATE, y = COUNT_SIGHTING)) +
  geom_col() +
  facet_wrap(~START_YEAR)
```


```{r}
vba_sbb_full |> 
  st_drop_geometry() |> 
  # filter(!is.na(FIRE_AGE)) |> 
  filter(FIRE_AGE_CATE == "3. Medium") |> 
  mutate(FIRE_AGE_BIN = cut(FIRE_AGE, breaks = c(seq(10,34,by=3)), include.lowest = TRUE, right = FALSE)) |>
  # select(FIRE_AGE,FIRE_AGE_BIN) |> arrange(FIRE_AGE) |> 
  group_by(START_YEAR, FIRE_AGE_BIN) |> 
  summarise(COUNT_SIGHTING = n()) |> 
  ggplot(aes(x = START_YEAR, y = COUNT_SIGHTING)) +
  geom_line(aes(color = FIRE_AGE_BIN))
```

# EVC

```{r}
vba_sbb_full |> 
  st_drop_geometry() |> 
  group_by(START_YEAR, EVC_GROUPNAME) |> 
  summarise(COUNT_SIGHTING = n()) |> 
  ggplot(aes(x = START_YEAR, y = COUNT_SIGHTING)) +
  geom_col() +
  facet_wrap(~EVC_GROUPNAME)

# Plot
# ggplot() +
#   geom_sf(data = vic_map) +
#   # geom_sf(data = parkres, fill=alpha("limegreen",0.5)) +
#   geom_sf(
#     data =
#       vba_sbb_full |>
#       filter(START_YEAR > 2020 
#              & EVC_GROUPNAME %in% c("Heathlands")),
#     color = "maroon",
#     size = 1
#   ) 
```

```{r}
vba_sbb_full |> 
  st_drop_geometry() |> 
  group_by(FIRE_AGE_CATE, EVC_GROUPNAME) |> 
  summarise(COUNT_SIGHTING = n()) |> 
  ggplot(aes(x = FIRE_AGE_CATE, y = COUNT_SIGHTING)) +
  geom_col() +
  facet_wrap(~EVC_GROUPNAME) +
  labs(title = "Sighting count by Fire Age Category for each EVC")
```

```{r}
vba_sbb_full |> 
  st_drop_geometry() |> 
  group_by(START_YEAR, FIRE_AGE_CATE, EVC_GROUPNAME) |> 
  summarise(COUNT_SIGHTING = n()) |> 
  filter(EVC_GROUPNAME == "Lowland Forests") |>
  ggplot() +
  geom_col(aes(x = START_YEAR, y = COUNT_SIGHTING, fill = FIRE_AGE_CATE), position = "dodge") +
  facet_wrap(~FIRE_AGE_CATE, ncol=1) +
  labs(title = "Lowland Forests: Sighting count by Fire Age Category")
```
```{r}
vba_sbb_full |> 
  st_drop_geometry() |> 
  group_by(START_YEAR, EVC_GROUPNAME, FIRE_AGE_CATE) |> 
  summarise(COUNT_SIGHTING = n()) |> 
  group_by(START_YEAR, EVC_GROUPNAME) |> 
  mutate(COUNT_SIGHTING_CPT = round(COUNT_SIGHTING/sum(COUNT_SIGHTING),4)) |> 
  filter(EVC_GROUPNAME %in% c("Lowland Forests","Heathy Woodlands","Heathlands")) |>
  ggplot() +
  geom_col(aes(x = START_YEAR, y = COUNT_SIGHTING_CPT, fill = FIRE_AGE_CATE)) +
  theme(legend.position = "top") +
  facet_wrap(~EVC_GROUPNAME, ncol=1) +
  labs(title = "How may % of yearly sightings are Recent?", 
       subtitle = "3 main ECVs: Heathlands, Heathy Woodlands, Lowland Forests")
```
- Declining occurrence in Unburnt areas  
- Increase in sightings in Recent and Early areas  

# Fire severity 

```{r}
vba_sbb_full |> 
  st_drop_geometry() |> 
  group_by(FIRE_SEVERITY, START_YEAR) |> 
  summarise(COUNT_SIGHTING = n()) |> 
  ggplot(aes(x = START_YEAR, y = COUNT_SIGHTING)) +
  geom_col() +
  facet_wrap(~FIRE_SEVERITY)
```

```{r}
```

