---
title: "Project Proposal: Bandicoots occurence in the Bunyip State Park"
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 2
editor: source
---

## Background & Objectives  

This analysis is a part of VNPA's project called "Caught on Camera (2012-2021)". A sub-project called "Spotlight on Bunyip in 2022" launched as the Southern Brown Bandicoots (*Isoodon obesulus obesulus*) is listed as an endangered species in Victoria.   

Initial aims were to investigate the impact of fire on habitat availability for a range of species, particularly small mammals and improve understanding of how fire impacts wildlife in the area to help land managers (Parks Victoria) improve the timing, location planning and techniques involved with planned burning and other currently employed land management operations.

Later the focus moved to finding Southern Brown Bandicoots across the park – especially after March 2019 when half the park burnt in a bushfire.  

## Initial Research Questions 

Project Questions: “What mammal species are located at ‘recently burnt’ and ‘long unburnt’ sites in Damp Heathy Woodland and Lowland Forest.”    

- What species are found in each EVC? 
- What species are found in each of the 4 categories of Time since fire? 
- What changes in species were found over the 10-year period? 
- (added later) Where are Southern Brown Bandicoots located within the park? 

::: {.callout-tip}
Analysis Question

Relationship between Southern Brown Bandicoots and time since fire, presence of predators, presence of competitors and ecological vegetation type?.  
:::



## Variables that may influence presence of Southern Brown Bandicoots  

1. Time since fire 
<!-- - ‘recently burnt’ sites are those that were burnt by wildfire in 2009 or 2008  -->
<!-- - ‘long unburnt’ sites were those that have not been burnt since 1970 -->

2. Presence of predators – foxes and cats 

3. Presence of habitat competitors - deer (Sambar and Fallow) 

4. Ecological Vegetation Class (EVC)  
Heathy Woodland and Lowland Forest are the main EVCs in Bunyip.

## Data sources

1. Wildlife sightings data  
- ALA  
[Atlas of Living Autralisa - Isoodon obesulus : Southern Brown Bandicoot](https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/e9e85f33-224c-40ce-b48d-290d1a41eb9d#)
- VBA   
[Victorian Biodiversity Atlas fauna records (unrestricted) for sites with high spatial accuracy](https://discover.data.vic.gov.au/dataset/victorian-biodiversity-atlas-fauna-records-unrestricted-for-sites-with-high-spatial-accuracy)
- VNPA internal surveyed data   



2. Fire history   
[Fire History Records of Fires across Victoria](https://discover.data.vic.gov.au/dataset/fire-history-records-of-fires-across-victoria)

3. EVC   
[Native Vegetation - Modelled 2005 Ecological Vegetation Classes (with Bioregional Conservation Status)](https://discover.data.vic.gov.au/dataset/native-vegetation-modelled-2005-ecological-vegetation-classes-with-bioregional-conservation-sta)



