---
title: "EDA Fire History"
subtitle: "Victoria 2019/2020 bushfires" 
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 2
editor: source
execute:
  echo: false
  message: false
  warning: false
---

```{r library}
# Library
lib <- c("targets","tarchetypes",
         "tidyverse","sf","galah","tmap","leaflet","plotly")
invisible(lapply(lib, library, character.only = TRUE))
rm(lib)

# Targets config
tar_config_set(store = here::here("_targets"))

# Create a custom theme
theme_minimal_hpha0042 <- theme_minimal() +
  theme(
    # Plot title & subtitle
    plot.title = element_text(face = 'bold'),
    plot.title.position = "plot",
    plot.subtitle = element_text(color = "grey20", size = 12)
  )
theme_set(theme_minimal_hpha0042)
```

```{r}
tar_load(vic_map)
tar_load(parkres)
tar_load(poly_laf)

tar_load(fire_history_1920)
tar_load(poly_fire_1920)
```

#### Fire extension

```{r}
# Define bounding box
bbox_fire_1920 <-
  st_bbox(
    c(
      xmin = 146.3000,
      xmax = sf::st_bbox(poly_fire_1920)[["xmax"]],
      ymin = -38,
      ymax = -35.3
    ),
    crs = st_crs(vic_map)
  )
  
# Plot megafires 2019/2020 extension
ggplot() + 
  geom_sf(data = vic_map) +
  geom_sf(data = poly_fire_1920, fill = alpha("darkred",0.4)) +
  geom_sf(data = parkres, fill = alpha("limegreen",0.4)) + 
  geom_sf(data = poly_laf, fill = "transparent", col = "orange", linewidth = 2) + 
  # Zoom
  coord_sf(xlim = bbox_fire_1920[c("xmin", "xmax")], ylim = bbox_fire_1920[c("ymin", "ymax")]) + 
  theme_bw() +
  labs(title = "Megafires 2019-2020 extension")
```

#### Fire Severity  

```{r}
fire_history_1920 |> 
  sf::st_drop_geometry() |> 
  group_by(FIRE_SVRTY) |>
  summarise(n = n())
```
```{r}

# fire_history_1920 |> st_area() |> sum()
#   filter(FIRE_SVRTY != "BURNT_NONFOREST" &
#            FIRE_SVRTY != "BURNT_UNKNOWN") |>
#   st_area() |> sum() 
# 3016584520 / 22485686093 [m^2] = 0.13 

# Plot megafires 2019/2020 extension
ggplot() + 
  geom_sf(data = vic_map) +
  geom_sf(data = fire_history_1920 |> 
            filter(FIRE_SVRTY != "BURNT_NONFOREST" & FIRE_SVRTY != "BURNT_UNKNOWN"),
          aes(fill = FIRE_SVRTY)) +
  # geom_sf(data = parkres, fill = alpha("limegreen",0.4)) + 
  geom_sf(data = poly_laf, fill = "transparent", col = "orange", linewidth = 2) + 
  # Zoom
  coord_sf(xlim = bbox_fire_1920[c("xmin", "xmax")], ylim = bbox_fire_1920[c("ymin", "ymax")]) + 
  theme_bw() +
  labs(title = "FIRE_SVRTY is only available for 13% of burnt areas")
```



```{r}
fire_history_1920 |> 
  sf::st_drop_geometry() |> 
  group_by(START_DATE) |>
  summarise(n = n()) |> 
  ggplot() +
  geom_col(aes(x = START_DATE, y = n), fill = "darkred") +
  labs(title = "Count fire record by Start Date", x = "Start Date", y = "No. of record")
```
::: {.callout-warning} 
Problems  
No FIRE_SVRTY specific classified data within LAF area.  
FIRE_SVRTY is only available for 13% of burnt areas.  
:::
