---
title: "EDA ALA sighting"
subtitle: "East Gippsland (extended area)" 
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 2
editor: source
execute:
  echo: false
  message: false
  warning: false
---

```{r library}
# Library
lib <- c("targets","tarchetypes",
         "tidyverse","sf","galah","terra",
         "tidyterra","tmap","leaflet","plotly")
invisible(lapply(lib, library, character.only = TRUE))
rm(lib)

# Targets config
tar_config_set(store = here::here("_targets"))

# Create a custom theme
theme_minimal_hpha0042 <- theme_minimal() +
  theme(
    # Plot title & subtitle
    plot.title = element_text(face = 'bold'),
    plot.title.position = "plot",
    plot.subtitle = element_text(color = "grey20", size = 12)
  )
theme_set(theme_minimal_hpha0042)
```

```{r}
#| label: load-data 
tar_load(vic_map)
tar_load(evc_cropped)
tar_load(poly_fire_1920)
tar_load(poly_filter_ala)
tar_load(ala_sighting)
tar_load(bbox_filter_ala)

tar_load(fire_history_eas)
```

### Data Wrangling

```{r}
ala_sighting |> sf::st_drop_geometry() |> select(speciesGroup) |> distinct() |> arrange()
```

```{r}
#| label: data-wrangling

# Data Wrangling 
ala_sighting <- ala_sighting |>
  # Add column
  dplyr::mutate(
    species_group = case_when(
    class == "Amphibia" ~ "Amphibians",
    speciesGroup == "Fungi" ~ "Fungi",
    .default = stringr::str_split_i(speciesGroup, " | ", -1)),
    eventDate = lubridate::as_date(eventDate, tz = "UTC")
  )

# Define important Dates
fire1920_start_date <- lubridate::ymd("2019-11-21")
# fire1920_start_date %m+% months(18) [1] "2021-05-21"
```

#### EVC Vegetation classes

There are 20 EVC vegetation classes `XGROUPNAME` in the study area.

```{r}
sort(unique(evc_cropped$XGROUPNAME))
```

### Data aggregation

#### Select species_groups

```{r}
# Crop fire extend 
poly <- sf::st_crop(st_make_valid(poly_fire_1920), st_make_valid(poly_filter_ala))

# Select species group ---------------------------------------------------------
# only those with ≥100 observations 
# [1] in burnt regions 
# [2] in the 18 months after fires were included for further analysis

ala_sighting_burnt <- 
  # [1] sighting in burnt regions
  sf::st_filter( 
    ala_sighting[c("species_group","sighting_date","geometry")], 
    poly) 

selected_species_group <- ala_sighting_burnt |> 
  sf::st_drop_geometry() |> 
  # [2] in the 18 months after fires 
  filter(
    sighting_date <= fire1920_start_date %m+% months(18)
  ) |>
  group_by(species_group) |>
  summarise(n = n()) |>
  filter(n >= 100) |>
  pull(species_group)

selected_species_group
```

Original data: 14 broad taxon groups `species_group`\
Selected species groups: only those with ≥100 observations \[1\] in burnt regions \[2\] in the 18 months after fires were included for further analysis

```{r}
ggplot() +
  geom_sf(data = vic_map,
          fill = "grey99", color = "grey70") +
  geom_sf(data = poly_fire_1920, fill = alpha("darkred",0.4)) + 
  geom_sf(data = poly_filter_ala, fill = "transparent", col = "orange", linewidth = 1)
```

```{r}
ggplot() +
  geom_sf(data = vic_map,
          fill = "grey99", color = "grey70") +
  geom_sf(
    data = ala_sighting |>
      filter(sighting_date >= "2019-11-21" &
             sighting_date <= ymd("2019-11-21") %m+% months(18)),
    aes(color = species_group),
    alpha = 0.5 , size = 1
  ) +
  # scale_color_manual(
    # values = pal,
    # name = "Species Group",
    # Legend
    # guide = guide_legend(nrow = 1, override.aes = list(size = 4, alpha = 1))
    # ) +
  # Zoom
  coord_sf(xlim = st_bbox(poly_filter_ala)[c("xmin", "xmax")], 
           ylim = st_bbox(poly_filter_ala)[c("ymin", "ymax")]) +
  labs(subtitle = "Jan 2017 - Jul 2023")
```

```{r}
#| fig-caption: "Which sighting records are in the burnt regions?"
ggplot() +
  geom_sf(
    data = vic_map, fill = "grey99", color = "grey70") +
  geom_sf(
    data = ala_sighting_burnt,
    alpha = 0.5 , size = 1
    ) +
  geom_sf(data = poly_fire_1920, fill = alpha("darkred",0.4)) +
  # Zoom
  coord_sf(xlim = st_bbox(poly_filter_ala)[c("xmin", "xmax")], 
           ylim = st_bbox(poly_filter_ala)[c("ymin", "ymax")]) +
  labs(subtitle = "Jan 2017 - Jul 2023")
```

```{r ARCHIVED}
#| eval: false
# Create grid cell using sf ---------------------------------------------------

## Grid sf object
grid <- st_make_grid(
    bbox_filter_ala, 
    cellsize = c(0.025, 0.025), # degree
    cellsize = units::as_units(25, "m"), # 25 x 25 m
    crs = st_crs(vic_map),
    what = "polygons",
    square = TRUE
    )
grid <- st_sf(grid_id = 1:length(lengths(grid)), grid) # Add grid ID

plot(st_bbox(grid |> filter(grid_id == 1)))

# No of grid: (0.25 x 0.25 degree) 12432
g1 <- sf::st_make_grid(
  bbox_filter_ala,
  cellsize = units::as_units(100, "km")) # length unit
# ------------------------------------------------------------------------------
```

#### gridcell

```{r}
# Create a SpatRaster grid template from scratch 
grid_template <- terra::rast(
  x = evc_cropped,
  crs = "epsg:7844", # GDA2020
  resolution = 1 / 3000
)
# Assign gridcell_id 
# terra::values(grid_template) <- 1:ncell(grid_template) # 68,950,350 rows

# names(grid_template) # [1] "lyr.1"
# Rename 
# grid_template <- grid_template |> 
#   tidyterra::rename(gridcell_id = lyr.1)

# head(as.data.frame(grid_template),100)

# Checking
# terra::cellSize(grid_template, unit = "m")

# Number of cells 
# length(terra::cells(grid_template)) 
# Values of cells 
# terra::values(grid_template)


# Checking Plot
# ggplot() +
#   geom_sf(
#     data = vic_map, fill = "grey99", color = "grey70") +
#   tidyterra::geom_spatraster(
#     data = grid_template,
#     aes(fill = lyr.1)
#     ) +
#   scale_fill_viridis_c(na.value = "transparent") +
#   # Zoom
#   coord_sf(xlim = st_bbox(poly_filter_ala)[c("xmin", "xmax")],
#            ylim = st_bbox(poly_filter_ala)[c("ymin", "ymax")]) +
#   labs(subtitle = "Check gridcell_id")

# Number of SIGHTINGS in each grid
# countgrid <- terra::rasterize(
#   vect(ala_sighting), 
#   grid_template, 
#   fun = "count", 
#   background = NA)

# Checking Plot
# ggplot() +
#   geom_sf(
#     data = vic_map, fill = "grey99", color = "grey70") +
#   tidyterra::geom_spatraster(
#     data = countgrid |> filter(!is.na(count)),
#     aes(fill = count)
#     ) +
#   scale_fill_viridis_c(na.value = "transparent") +
#   # Zoom
#   coord_sf(xlim = st_bbox(poly_filter_ala)[c("xmin", "xmax")],
#            ylim = st_bbox(poly_filter_ala)[c("ymin", "ymax")]) +
#   labs(subtitle = "Count of sightings in each 1000 m^2 grid cell")
```

```{r}
# Convert sf EVC polygons to terra::SpatVector
evc_cropped_v <- terra::vect(evc_cropped[c("XGROUPNAME", "geometry")])

# rasterize EVC polygons XGROUPNAME to each grid cells
gridcell <- terra::rasterize(
  evc_cropped_v, # SpatVector object
  grid_template, # SpatRaster grid cell template
  field = "XGROUPNAME", # EVC class
  )

# Preview gridcell SpatRaster value
head(gridcell)

# Checking Plot
ggplot() +
  geom_spatraster(data = gridcell) +
  scale_fill_viridis_d(na.value = "transparent") +  # Optional color scale
  labs(subtitle = "Vegetation class 'XGROUPNAME' of each grid cell",
       fill = "EVC Name") + 
  theme_minimal() +
  theme(legend.position = "none")
```

```{r}
#| eval: false
# Count how many grid cells each EVC class covers? 
gridcell |> as.data.frame() |> # only retain cells with !is.na(XGROUPNAME)
  rownames_to_column() |> 
  select(rowname) |> unique() |> nrow()
  dplyr::group_by(XGROUPNAME) |> 
  dplyr::summarise(n = n())

gridcell_df <- terra::as.data.frame(gridcell, cells = TRUE) |> 
  dplyr::mutate(XGROUPNAME = as.character(XGROUPNAME)) 
# nrow(gridcell_df)
# 35,289,585 rows
```

#### Sighting 

```{r}
selected_species_group <-  c("Amphibians", "Arthropods", "Birds", "Crustaceans", "Fishes", "Fungi", "Insects", "Mammals", "Molluscs", "Plants", "Reptiles")

Sys.time()
sighting <- ala_sighting |>
  # Subset necessary columns
  dplyr::select(sighting_id = recordID, species_group, sighting_date = eventDate, sighting_geometry = geometry) |> 
  # Subset records
  dplyr::filter(species_group %in% selected_species_group) |>
  # Join sighting POINTS with fire POLYGONS
  sf::st_join(fire_history_eas |> janitor::clean_names(),
          join = st_within, left = TRUE) |> 
  # Get the latest fire record of each sighting
  dplyr::filter(is.na(fire_start_date) | fire_start_date <= sighting_date) |>
  dplyr::group_by(sighting_id) |> 
  dplyr::filter(is.na(fire_start_date) | fire_start_date == max(fire_start_date)) |> 
  dplyr::ungroup() |> 
  # Join sighting POINTS with with EVC POLYGONS
  st_join(evc_cropped |> select(evc_group = XGROUPNAME) |> janitor::clean_names(),
          join = st_within, left = TRUE) |> 
  # Exclude records without evc_group 
  dplyr::filter(!is.na(evc_group)) |>
  # Add columns ---------
  dplyr::mutate(
    before_after_fire = case_when(
      sighting_date < fire1920_start_date ~ "before",
      sighting_date >= fire1920_start_date ~ "after" ),
    burnt = if_else(!is.na(fire_start_date) & ymd(fire_start_date) < sighting_date, 
      "burnt", 
      "unburnt"),
    sample = paste(burnt, before_after_fire, sep = "_"),
    time_since_fire_days = if_else(burnt == "burnt",
      as.numeric(lubridate::ymd(sighting_date) - lubridate::ymd(fire_start_date)),
      NA)
  ) 
  # --------------------- 
Sys.time()

# CHECKING: nrow(sighting) < nrow(ala_sighting) <- excluded FIRE_START_DATE > sighting_date, only selected_species_group

# CHECKING: How many sighting records with NA evc_group? 
# nrow(sighting |> filter(is.na(evc_group))) # 120,234 rows

# --------------------------------------------------------------------------------------
# Solution 1: sighting + (evc + grid_tempalte) = sighting + gridcell = sighting_gridcell

# Convert sf point to terra SpatVector
sighting_v <- terra::vect(sighting)

# Extract Vegetation class for each sighting record
sighting_gridcell <- terra::extract(
  x = gridcell,
  y = sighting_v,
  cells = TRUE
  # ID = TRUE # the first column returned has the IDs (record numbers) of y
)
sighting_gridcell_df <- terra::as.data.frame(sighting_gridcell, geom=NULL)

length(unique(sighting_gridcell_df$cell)) # 55784 unique grid cell
# --------------------------------------------------------------------------------------


# Solution 2: (sighting + evc) + grid_template = sighting_gridcell 

# Create a SpatRaster grid template from scratch 
grid_template <- terra::rast(
  x = sighting,
  crs = "epsg:7844", # GDA2020
  resolution = 1 / 3000
)
# Assign gridcell_id 
# terra::values(grid_template) <- 1:ncell(grid_template) # 68,401,743 rows

# Convert sf point to terra SpatVector
sighting_v <- terra::vect(sighting)

# Rasterise sighting sf POINTS to each grid cells (SpatRaster)
gridcell <- terra::rasterize(
  sighting_v, # SpatVector object
  grid_template, # SpatRaster grid cell template
  field = c("sighting_id"), # EVC class
  )

# Extract Vegetation class for each sighting record
sighting_gridcell <- terra::extract(
  x = gridcell,
  y = sighting_v,
  cells = TRUE
  # ID = TRUE # the first column returned has the IDs (record numbers) of y
) |> 
  dplyr::mutate(sighting_id = as.character(sighting_id))

sighting_2 <- sighting |> 
  inner_join(sighting_gridcell, by = c("sighting_id"))

# Preview gridcell SpatRaster value
# as.matrix(gridcell) |> as.data.frame() |> nrow()
# 
# terra::as.data.frame(gridcell) |> 
#   # tibble::rownames_to_column() |> 
#   group_by(rowname) |> 
#   summarise(n=n()) |> 
#   arrange(desc(n))
```

```{r}
#| eval: false 
# CHECKING PLOT: Why some sighting_id do not have evc_group? 
ggplot() + 
  geom_sf(data = evc_cropped, 
          aes(fill = XGROUPNAME), col = "transparent") + 
  geom_sf(data = sighting |> select(c(sighting_id, sighting_geometry, evc_group)) |> filter(is.na(evc_group)),
          ) +
  theme(legend.position = "none")

sighting |> 
  select(c(sighting_id, sighting_geometry, evc_group,species_group)) |> 
  filter(is.na(evc_group)) |> 
  group_by(species_group) |> 
  summarise(n = n())
```


#### Fire
```{r}

# colnames(fire_history_eas)
# > [1] "FIRE_SEASON","FIRE_NO","FIRE_START_DATE","FIRE_SVRTY","geometry" 
# nrow(fire_history_eas) 
# > [1] 537303 records
```

